AWSTemplateFormatVersion: '2010-09-09'
Description: Target Group IP y Listener Rule para enrutar ALB hacia API Gateway privada

Parameters:
  VpcId:
    Type: String
    Default: vpc-06a3c67543fa27054
  Subnet1:
    Type: String
    Default: subnet-0bb2fc1b28785d305
  Subnet2:
    Type: String
    Default: subnet-07e520734b5f52c71
  AlbListenerArn:
    Type: String
    Default: arn:aws:elasticloadbalancing:us-east-1:381492081993:listener/app/pocalb-Internal-ALB/f66cce68f43b3f2c/a7c0e4c07c2e109d

Resources:
  ApiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-api-private
      Protocol: HTTPS
      Port: 443
      TargetType: ip
      VpcId: !Ref VpcId
      Targets:
        - Id: 10.0.142.209
        - Id: 10.0.153.193
      HealthCheckProtocol: HTTPS
      HealthCheckPath: /
      Matcher:
        HttpCode: 200-499

  ApiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref AlbListenerArn
      Priority: 16
      Conditions:
        - Field: path-pattern
          Values:
            - /api/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ApiTargetGroup